import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { CalendarDays, Clock3, MapPin, QrCode } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useCatalog } from '../../hooks/useAvailability';
import { bookingService } from '../../services/booking';
import { Button, EmptyState, ErrorState, Loading, Modal, StatusBadge } from '../../components/ui';
import { OtpForm } from '../../features/auth/OtpForm';
import { RescheduleForm } from '../../features/booking/RescheduleForm';
import type { Reservation } from '../../types/domain';
import { formatDate, shortTime } from '../../utils/date';

type Filter = 'upcoming' | 'history' | 'cancelled';
export function ReservationsPage() {
  const { user, loading } = useAuth(); const client = useQueryClient(); const catalog = useCatalog();
  const [filter, setFilter] = useState<Filter>('upcoming'); const [action, setAction] = useState<{ kind: 'cancel' | 'reschedule'; reservation: Reservation } | null>(null); const [notice, setNotice] = useState('');
  const reservations = useQuery({ queryKey: ['reservations', user?.id], queryFn: bookingService.reservations, enabled: !!user, refetchInterval: 30_000 });
  const cancel = useMutation({ mutationFn: (id: string) => bookingService.cancel(id), onSuccess: () => { setAction(null); setNotice('Tu reserva fue cancelada y el carril está nuevamente disponible.'); void client.invalidateQueries({ queryKey: ['reservations'] }); void client.invalidateQueries({ queryKey: ['availability'] }); } });
  const rows = (reservations.data || []).filter(row => filter === 'cancelled' ? row.status === 'CANCELLED' : filter === 'upcoming' ? ['CONFIRMED', 'CHECKED_IN'].includes(row.status) && Date.parse(row.ends_at) > Date.now() : row.status !== 'CANCELLED' && (!['CONFIRMED', 'CHECKED_IN'].includes(row.status) || Date.parse(row.ends_at) <= Date.now())).sort((a, b) => filter === 'upcoming' ? a.starts_at.localeCompare(b.starts_at) : b.starts_at.localeCompare(a.starts_at));
  return <div className="container public-section"><header className="page-heading"><div><p className="eyebrow">TU CUENTA EMUSS</p><h1>Mis reservas</h1><p className="muted">Tus próximos encuentros con el agua, en un solo lugar.</p></div><Link className="button button-primary" to="/">Reservar un carril</Link></header>{loading ? <Loading /> : !user ? <section className="panel auth-panel"><h2>Ingresa con tu correo</h2><OtpForm /></section> : <>{notice && <p role="status" className="success-state">{notice}</p>}<div className="tabs" role="tablist" aria-label="Filtrar reservas">{([['upcoming', 'Próximas reservas'], ['history', 'Historial'], ['cancelled', 'Canceladas']] as const).map(([value, label]) => <button key={value} role="tab" aria-selected={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div>{reservations.isPending ? <Loading label="Buscando tus reservas…" /> : reservations.isError ? <ErrorState error={reservations.error} onRetry={() => { void reservations.refetch(); }} /> : !rows.length ? <EmptyState title="No encontramos reservas" description={filter === 'upcoming' ? 'Elige una sede y reserva tu próximo entrenamiento.' : 'Las reservas de esta categoría aparecerán aquí.'}><Link className="button button-secondary" to="/">Explorar disponibilidad</Link></EmptyState> : <div className="reservation-list">{rows.map(row => {
    const changeAllowed = !!catalog.data && row.status === 'CONFIRMED' && Date.parse(row.starts_at) - Date.now() >= catalog.data.settings.cancellation_hours * 3_600_000;
    return <article className="panel reservation-card" key={row.id}><div className="reservation-date"><CalendarDays size={23} /><strong>{new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'short', timeZone: 'America/Lima' }).format(new Date(row.starts_at))}</strong><span>{shortTime(row.start_time)}</span></div><div className="reservation-info"><div className="row wrap"><h2>{row.venue_name}</h2><StatusBadge status={row.status} /></div><p><MapPin size={15} />{row.pool_name} · Carril {row.lane_number}</p><p><Clock3 size={15} />{formatDate(row.date)} · {shortTime(row.start_time)} – {shortTime(row.end_time)}</p><code>{row.reservation_code}</code></div><div className="reservation-actions"><Link className="button button-secondary" to={`/reserva/${encodeURIComponent(row.reservation_code)}`}><QrCode size={17} />Ver QR y comprobante</Link>{changeAllowed && <div className="row wrap">{catalog.data?.settings.reschedule_enabled && <Button variant="ghost" onClick={() => { setAction({ kind: 'reschedule', reservation: row }); cancel.reset(); }}>Reprogramar</Button>}<Button variant="ghost" onClick={() => { setAction({ kind: 'cancel', reservation: row }); cancel.reset(); }}>Cancelar</Button></div>}{row.status === 'CONFIRMED' && catalog.data && !changeAllowed && <small className="muted">El plazo para cambios ha terminado.</small>}</div></article>;
  })}</div>}{catalog.data && <p className="booking-policy">Cancelaciones hasta {catalog.data.settings.cancellation_hours} horas antes del inicio. Horarios en Lima, Perú.</p>}</>}{action && <Modal title={action.kind === 'cancel' ? 'Cancelar reserva' : 'Reprogramar reserva'} onClose={() => { if (!cancel.isPending) setAction(null); }}>{action.kind === 'cancel' ? <div className="stack"><p>Cancelarás <strong>{action.reservation.reservation_code}</strong>, del {formatDate(action.reservation.date)} a las {shortTime(action.reservation.start_time)}. El carril quedará disponible para otras personas.</p>{cancel.isError && <ErrorState error={cancel.error} />}<div className="row wrap"><Button variant="secondary" disabled={cancel.isPending} onClick={() => setAction(null)}>Conservar reserva</Button><Button variant="danger" loading={cancel.isPending} onClick={() => cancel.mutate(action.reservation.id)}>Sí, cancelar reserva</Button></div></div> : <RescheduleForm reservation={action.reservation} onSuccess={() => { setAction(null); setNotice('Tu reserva fue reprogramada. Ya puedes consultar el comprobante actualizado.'); }} />}</Modal>}</div>;
}
