import { useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { CalendarPlus, RefreshCw, Wrench } from 'lucide-react';
import { Button, Field, Input, Modal, Select, StatusBadge } from '../../components/ui';
import { useAvailability } from '../../hooks/useAvailability';
import { admin, type Maintenance } from '../../services/admin';
import type { Availability } from '../../types/domain';
import { shortTime, todayLima } from '../../utils/date';
import { AdminHeading, dateTime, emptyFilters, laneNames, Notice, QueryState, useAdminCatalog, usePermissions, useRefreshAdmin } from './common';
import { ReservationDetails } from './ReservationsPage';

function MaintenanceForm({ poolId = '', laneId, startsAt, onDone }: { poolId?: string; laneId?: string; startsAt?: string; onDone: () => void }) {
  const catalog = useAdminCatalog(); const permissions = usePermissions(); const [pool, setPool] = useState(poolId); const [lanes, setLanes] = useState<string[]>(laneId ? [laneId] : []); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: (values: { from: string; to: string; reason: string }) => admin.maintenance(pool, lanes.length ? lanes : null, `${values.from}:00-05:00`, `${values.to}:00-05:00`, values.reason), onSuccess: () => { void refresh(); onDone(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const from = String(data.get('from')); const to = String(data.get('to')); if (to <= from) { event.currentTarget.reportValidity(); return; } mutation.mutate({ from, to, reason: String(data.get('reason')).trim() }); }
  const [fromDate, setFromDate] = useState(startsAt ? startsAt.slice(0, 16) : `${todayLima()}T08:00`);
  return <form className="stack" onSubmit={submit}><p className="muted">Los bloques con reservas activas no se pueden cerrar. Resuelve esas reservas antes de crear el mantenimiento.</p><Field label="Piscina"><Select value={pool} required onChange={event => { setPool(event.target.value); setLanes([]); }}><option value="">Selecciona una piscina</option>{catalog.data?.pools.filter(item => permissions.canManage(item.venue_id)).map(item => <option key={item.id} value={item.id}>{catalog.data?.venues.find(venue => venue.id === item.venue_id)?.name} · {item.name}</option>)}</Select></Field><fieldset className="admin-checkbox-group"><legend>Carriles</legend><p className="muted">Sin selección: se bloquea la piscina completa.</p>{catalog.data?.lanes.filter(lane => lane.pool_id === pool).map(lane => <label key={lane.id}><input type="checkbox" checked={lanes.includes(lane.id)} onChange={event => setLanes(event.target.checked ? [...lanes, lane.id] : lanes.filter(id => id !== lane.id))} /> Carril {lane.number}</label>)}</fieldset><div className="admin-form-grid"><Field label="Desde (hora de Lima)"><Input type="datetime-local" name="from" required value={fromDate} onChange={event => setFromDate(event.target.value)} /></Field><Field label="Hasta (hora de Lima)"><Input type="datetime-local" name="to" min={fromDate} required defaultValue={startsAt ? `${startsAt.slice(0, 10)}T18:00` : `${todayLima()}T18:00`} /></Field></div><Field label="Motivo"><Input name="reason" required minLength={5} maxLength={500} placeholder="Ej. Mantenimiento preventivo del sistema de filtrado" /></Field><Notice error={mutation.error || catalog.error} /><Button type="submit" loading={mutation.isPending} disabled={!pool}><Wrench size={16} /> Crear mantenimiento</Button></form>;
}
function ManualReservation({ row, onDone }: { row: Availability; onDone: () => void }) {
  const users = useQuery({ queryKey: ['admin', 'users'], queryFn: () => admin.list('users') }); const [search, setSearch] = useState(''); const [user, setUser] = useState(''); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: () => admin.createReservation(user, row.lane_id, row.time_slot_id), onSuccess: () => { void refresh(); onDone(); } });
  const matches = users.data?.filter(customer => `${customer.first_name} ${customer.last_name} ${customer.email}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="stack"><p className="muted">Reserva para un cliente con cuenta verificada. El sistema validará el carril y evitará reservas simultáneas del mismo cliente.</p><Field label="Buscar cliente registrado"><Input type="search" value={search} onChange={event => { setSearch(event.target.value); setUser(''); }} placeholder="Nombre o correo" /></Field><QueryState pending={users.isPending} error={users.error} empty={!matches.length} emptyText="No encontramos clientes registrados."><Field label="Cliente"><Select value={user} onChange={event => setUser(event.target.value)}><option value="">Selecciona al cliente</option>{matches.slice(0, 100).map(customer => <option key={customer.id} value={customer.id}>{customer.first_name} {customer.last_name} · {customer.email}</option>)}</Select></Field></QueryState><Notice error={mutation.error} /><Button disabled={!user} loading={mutation.isPending} onClick={() => mutation.mutate()}><CalendarPlus size={17} /> Confirmar reserva manual</Button></div>;
}
function ControlSelection({ row, onClose }: { row: Availability; onClose: () => void }) {
  const [action, setAction] = useState<'manual' | 'maintenance' | null>(null); const permissions = usePermissions();
  const occupied = row.status === 'RESERVED' || row.status === 'CHECKED_IN';
  const query = useQuery({ queryKey: ['admin', 'control-reservation', row.time_slot_id, row.lane_id], queryFn: () => admin.reservations({ ...emptyFilters(), from: row.date, to: row.date, pool: row.pool_id, lane: row.lane_id }, 100), enabled: occupied });
  const reservation = query.data?.rows.find(item => item.time_slot_id === row.time_slot_id && item.status !== 'CANCELLED');
  if (reservation) return <ReservationDetails reservation={reservation} onClose={onClose} />;
  return <Modal title={`Carril ${row.number} · ${shortTime(row.start_time)} – ${shortTime(row.end_time)}`} onClose={onClose}><div className="stack"><p>{row.venue_name} · {row.pool_name} · {row.date}</p><StatusBadge status={row.status} />{occupied ? <QueryState pending={query.isPending} error={query.error} empty={!reservation} emptyText="La reserva cambió. Actualiza el control de piscina." onRetry={() => void query.refetch()}><span /></QueryState> : row.status === 'AVAILABLE' && permissions.canManage(row.venue_id) ? <><div className="admin-actions"><Button variant={action === 'manual' ? 'primary' : 'secondary'} onClick={() => setAction('manual')}><CalendarPlus size={16} /> Reserva manual</Button><Button variant={action === 'maintenance' ? 'primary' : 'secondary'} onClick={() => setAction('maintenance')}><Wrench size={16} /> Mantenimiento</Button></div>{action === 'manual' && <ManualReservation row={row} onDone={onClose} />}{action === 'maintenance' && <MaintenanceForm poolId={row.pool_id} laneId={row.lane_id} startsAt={`${row.date}T${shortTime(row.start_time)}`} onDone={onClose} />}</> : <p className="muted">{row.status === 'HELD' ? 'Un cliente está completando su reserva. El bloqueo temporal se libera automáticamente al vencer.' : 'Este carril no está habilitado para nuevas reservas.'}</p>}</div></Modal>;
}
export function ControlPage() {
  const catalog = useAdminCatalog(); const [date, setDate] = useState(todayLima()); const [poolId, setPoolId] = useState(''); const [selected, setSelected] = useState<Availability | null>(null);
  const permissions = usePermissions(); const pools = catalog.data?.pools.filter(pool => pool.active && permissions.canManage(pool.venue_id)) || []; const pool = poolId || pools[0]?.id || '';
  const query = useAvailability(date, pool || undefined); const rows = query.data?.filter(row => row.pool_id === pool) || [];
  const lanes = catalog.data?.lanes.filter(lane => lane.pool_id === pool && lane.active).sort((a, b) => a.number - b.number) || [];
  const slots = [...new Map(rows.map(row => [row.time_slot_id, row])).values()].sort((a, b) => a.start_time.localeCompare(b.start_time));
  return <div className="admin-page"><AdminHeading title="Control de piscina" description="Cada celda representa un carril completo durante un bloque horario." actions={<Button variant="secondary" loading={query.isFetching} onClick={() => void query.refetch()}><RefreshCw size={16} /> Actualizar</Button>} /><div className="panel admin-filter-grid"><Field label="Fecha"><Input type="date" value={date} required onChange={event => setDate(event.target.value)} /></Field><Field label="Piscina"><Select value={pool} onChange={event => setPoolId(event.target.value)}><option value="" disabled>Selecciona piscina</option>{pools.map(item => <option key={item.id} value={item.id}>{catalog.data?.venues.find(venue => venue.id === item.venue_id)?.name} · {item.name}</option>)}</Select></Field></div><Notice error={catalog.error} /><div className="admin-lane-legend">{Object.entries(laneNames).map(([key, label]) => <span key={key}><i className={`admin-state-dot state-${key.toLowerCase()}`} />{label}</span>)}</div><section className="panel"><div className="admin-section-heading"><h2>{pools.find(item => item.id === pool)?.name || 'Disponibilidad'}</h2><span className="muted">Selecciona una celda para gestionar</span></div><QueryState pending={query.isPending || catalog.isPending} error={query.error} empty={!slots.length} emptyText="No hay horarios habilitados para esta fecha." onRetry={() => void query.refetch()}><div className="admin-table-wrap admin-control-table"><table><thead><tr><th>Horario</th>{lanes.map(lane => <th key={lane.id}>Carril {lane.number}</th>)}</tr></thead><tbody>{slots.map(slot => <tr key={slot.time_slot_id}><th><strong>{shortTime(slot.start_time)}</strong><small>{shortTime(slot.end_time)}</small></th>{lanes.map(lane => { const row = rows.find(item => item.time_slot_id === slot.time_slot_id && item.lane_id === lane.id); return <td key={lane.id}>{row ? <button className={`admin-lane-cell state-${row.status.toLowerCase()}`} aria-label={`${shortTime(slot.start_time)}, carril ${lane.number}: ${laneNames[row.status]}`} onClick={() => setSelected(row)}><i /><span>{laneNames[row.status]}</span></button> : <span aria-label="Sin horario">—</span>}</td>; })}</tr>)}</tbody></table></div></QueryState></section>{selected && <ControlSelection row={selected} onClose={() => { setSelected(null); void query.refetch(); }} />}</div>;
}
export function MaintenancePage() {
  const [creating, setCreating] = useState(false); const [removing, setRemoving] = useState<Maintenance | null>(null); const refresh = useRefreshAdmin();
  const query = useQuery({ queryKey: ['admin', 'maintenance'], queryFn: () => admin.list('maintenance_blocks') }); const catalog = useAdminCatalog();
  const mutation = useMutation({ mutationFn: (id: string) => admin.removeMaintenance(id), onSuccess: () => { setRemoving(null); void refresh(); } });
  return <div className="admin-page"><AdminHeading title="Mantenimiento" description="Programa cierres de carriles o piscinas y protege su disponibilidad." actions={<Button onClick={() => setCreating(true)}><Wrench size={16} /> Programar mantenimiento</Button>} /><Notice error={mutation.error} success={mutation.isSuccess ? 'Mantenimiento retirado.' : undefined} /><section className="panel"><QueryState pending={query.isPending} error={query.error} empty={!query.data?.length} onRetry={() => void query.refetch()} emptyText="No hay mantenimientos programados."><div className="admin-table-wrap"><table><thead><tr><th>Piscina</th><th>Alcance</th><th>Desde</th><th>Hasta</th><th>Motivo</th><th>Acciones</th></tr></thead><tbody>{query.data?.map(item => <tr key={item.id}><td><strong>{item.venue_name}</strong><small>{item.pool_name}</small></td><td>{item.lane_id ? `Carril ${catalog.data?.lanes.find(lane => lane.id === item.lane_id)?.number || '—'}` : 'Piscina completa'}</td><td>{dateTime(item.starts_at)}</td><td>{dateTime(item.ends_at)}</td><td>{item.reason}</td><td><Button variant="ghost" onClick={() => setRemoving(item)}>Retirar bloqueo</Button></td></tr>)}</tbody></table></div></QueryState></section>{creating && <Modal title="Programar mantenimiento" onClose={() => setCreating(false)} wide><MaintenanceForm onDone={() => setCreating(false)} /></Modal>}{removing && <Modal title="Retirar mantenimiento" onClose={() => setRemoving(null)}><p>Se retirará el bloqueo «{removing.reason}». Los horarios volverán a estar sujetos a la disponibilidad actual.</p><Notice error={mutation.error} /><Button variant="danger" loading={mutation.isPending} onClick={() => mutation.mutate(removing.id)}>Confirmar retiro</Button></Modal>}</div>;
}
