import { useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { History, MailPlus, Pencil, ShieldCheck } from 'lucide-react';
import { Button, Field, Input, Modal, Select } from '../../components/ui';
import { admin, type Customer, type Staff } from '../../services/admin';
import type { Reservation, Role } from '../../types/domain';
import { AdminHeading, dateTime, emptyFilters, Notice, Pagination, QueryState, roleNames, useAdminCatalog, useRefreshAdmin } from './common';
import { ReservationDetails, ReservationTable } from './ReservationsPage';

function CustomerHistory({ customer, onClose }: { customer: Customer; onClose: () => void }) {
  const [page, setPage] = useState(0); const [selected, setSelected] = useState<Reservation | null>(null);
  const query = useQuery({ queryKey: ['admin', 'customer-history', customer.id, page], queryFn: () => admin.reservations({ ...emptyFilters(), from: '2000-01-01', to: '2100-12-31' }, 25, page * 25, customer.id) });
  return <>{selected ? <ReservationDetails reservation={selected} onClose={() => setSelected(null)} /> : <Modal title={`${customer.first_name} ${customer.last_name}`} onClose={onClose} wide><p className="muted">{customer.email} · DNI {customer.dni_masked}</p><div className="admin-customer-stats"><span><strong>{customer.reservations}</strong> Reservas</span><span><strong>{customer.attendances}</strong> Asistencias</span><span><strong>{customer.cancellations}</strong> Cancelaciones</span><span><strong>{customer.no_shows}</strong> No-show</span></div><QueryState pending={query.isPending} error={query.error} empty={!query.data?.rows.length} onRetry={() => void query.refetch()} emptyText="Este cliente aún no tiene reservas."><ReservationTable rows={query.data?.rows || []} onSelect={setSelected} /></QueryState><Pagination page={page} count={query.data?.total || 0} onChange={setPage} busy={query.isFetching} /></Modal>}</>;
}
export function UsersPage() {
  const query = useQuery({ queryKey: ['admin', 'users'], queryFn: () => admin.list('users') }); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [selected, setSelected] = useState<Customer | null>(null);
  const rows = query.data?.filter(row => `${row.first_name} ${row.last_name} ${row.email}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="admin-page"><AdminHeading title="Clientes" description="Conoce la participación y el historial de los usuarios de tus sedes." /><section className="panel admin-filters"><Field label="Buscar cliente"><Input type="search" placeholder="Nombre o correo" value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} /></Field></section><section className="panel"><QueryState pending={query.isPending} error={query.error} empty={!rows.length} onRetry={() => void query.refetch()} emptyText="No encontramos clientes."><div className="admin-table-wrap"><table><thead><tr><th>Cliente</th><th>Reservas</th><th>Asistencias</th><th>Cancelaciones</th><th>No-show</th><th>Última reserva</th><th>Acciones</th></tr></thead><tbody>{rows.slice(page * 25, (page + 1) * 25).map(row => <tr key={row.id}><td><strong>{row.first_name} {row.last_name}</strong><small>{row.email}</small></td><td>{row.reservations}</td><td>{row.attendances}</td><td>{row.cancellations}</td><td>{row.no_shows}</td><td>{row.last_reservation ? dateTime(row.last_reservation) : '—'}</td><td><Button variant="ghost" onClick={() => setSelected(row)}><History size={16} /> Historial</Button></td></tr>)}</tbody></table></div></QueryState><Pagination page={page} count={rows.length} onChange={setPage} /></section>{selected && <CustomerHistory customer={selected} onClose={() => setSelected(null)} />}</div>;
}
function StaffEditor({ staff, onClose }: { staff: Staff | null; onClose: () => void }) {
  const catalog = useAdminCatalog(); const refresh = useRefreshAdmin(); const [role, setRole] = useState<Role>(staff?.role || 'RECEPTIONIST'); const [active, setActive] = useState(staff?.active ?? true);
  const mutation = useMutation({ mutationFn: async (form: FormData) => {
    const venue = role === 'SUPER_ADMIN' ? null : String(form.get('venue_id'));
    if (staff) return admin.staffRole(staff.user_id, role, venue, active);
    return admin.invite({ email: String(form.get('email')).trim(), first_name: String(form.get('first_name')).trim(), last_name: String(form.get('last_name')).trim(), role, venue_id: venue });
  }, onSuccess: () => { void refresh(); onClose(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); mutation.mutate(new FormData(event.currentTarget)); }
  return <Modal title={staff ? 'Editar acceso del trabajador' : 'Invitar trabajador'} onClose={onClose}><form className="stack" onSubmit={submit}>{staff ? <div><strong>{staff.first_name} {staff.last_name}</strong><p className="muted">{staff.email}</p></div> : <><div className="admin-form-grid"><Field label="Nombre"><Input name="first_name" required minLength={2} maxLength={80} /></Field><Field label="Apellido"><Input name="last_name" required minLength={2} maxLength={80} /></Field></div><Field label="Correo de trabajo"><Input name="email" type="email" required autoComplete="email" /></Field></>}<Field label="Rol"><Select value={role} onChange={event => setRole(event.target.value as Role)}>{Object.entries(roleNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field>{role !== 'SUPER_ADMIN' && <Field label="Sede asignada"><Select name="venue_id" required defaultValue={staff?.venue_id || ''}><option value="">Selecciona una sede</option>{catalog.data?.venues.filter(venue => venue.active).map(venue => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</Select></Field>}<div className="admin-insight"><ShieldCheck size={18} /><p>{role === 'SUPER_ADMIN' ? 'Acceso a todas las sedes, configuración, trabajadores y auditoría.' : role === 'VENUE_ADMIN' ? 'Gestión de reservas, mantenimiento y reportes de la sede asignada.' : 'Consulta de reservas, búsqueda de códigos y check-in de la sede asignada.'}</p></div>{staff && <><label className="admin-checkbox"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} /> Acceso activo</label>{!active && <p className="admin-notice error">Al guardar, el trabajador perderá este acceso administrativo.</p>}</>}<Notice error={mutation.error || catalog.error} /><Button type="submit" loading={mutation.isPending}>{staff ? 'Guardar acceso' : 'Enviar invitación'}</Button>{!staff && <p className="muted">El trabajador recibirá un correo para activar su cuenta y establecer una contraseña.</p>}</form></Modal>;
}
export function StaffPage() {
  const query = useQuery({ queryKey: ['admin', 'staff'], queryFn: () => admin.list('user_roles') }); const [editing, setEditing] = useState<{ row: Staff | null } | null>(null); const [success, setSuccess] = useState('');
  return <div className="admin-page"><AdminHeading title="Equipo administrativo" description="Asigna responsabilidades y controla el acceso a cada sede." actions={<Button onClick={() => { setSuccess(''); setEditing({ row: null }); }}><MailPlus size={17} /> Invitar trabajador</Button>} /><Notice success={success} /><section className="panel"><QueryState pending={query.isPending} error={query.error} empty={!query.data?.length} onRetry={() => void query.refetch()} emptyText="No hay trabajadores registrados."><div className="admin-table-wrap"><table><thead><tr><th>Trabajador</th><th>Rol</th><th>Sede</th><th>Acceso</th><th>Acciones</th></tr></thead><tbody>{query.data?.map(row => <tr key={row.id}><td><strong>{row.first_name} {row.last_name}</strong><small>{row.email}</small></td><td>{roleNames[row.role]}</td><td>{row.venue_name || 'Todas las sedes'}</td><td><span className={`badge ${row.active ? 'status-available' : 'status-maintenance'}`}>{row.active ? 'Activo' : 'Desactivado'}</span></td><td><Button variant="ghost" onClick={() => { setSuccess(''); setEditing({ row }); }}><Pencil size={15} /> Editar acceso</Button></td></tr>)}</tbody></table></div></QueryState></section>{editing && <StaffEditor staff={editing.row} onClose={() => setEditing(null)} />}</div>;
}
const actionNames: Record<string, string> = { RESERVATION_CREATED: 'Creó una reserva', RESERVATION_CANCELLED: 'Canceló una reserva', RESERVATION_RESCHEDULED: 'Reprogramó una reserva', CHECK_IN: 'Registró un check-in', MAINTENANCE_CREATED: 'Programó mantenimiento', MAINTENANCE_REMOVED: 'Retiró mantenimiento', STAFF_ROLE_UPDATED: 'Actualizó un acceso', STAFF_INVITED: 'Invitó a un trabajador', SETTINGS_UPDATED: 'Actualizó la configuración', SLOTS_GENERATED: 'Publicó horarios' };
const entityNames: Record<string, string> = { reservations: 'Reserva', maintenance_blocks: 'Mantenimiento', user_roles: 'Acceso administrativo', venues: 'Sede', pools: 'Piscina', lanes: 'Carril', settings: 'Configuración', schedule_templates: 'Horario', holidays: 'Feriado', time_slots: 'Bloque horario' };
export function AuditPage() {
  const query = useQuery({ queryKey: ['admin', 'audit'], queryFn: () => admin.list('audit_logs'), refetchInterval: 30_000 }); const [search, setSearch] = useState(''); const [page, setPage] = useState(0);
  const rows = query.data?.filter(row => `${row.actor_name} ${row.action} ${actionNames[row.action] || ''} ${row.entity_type} ${row.entity_id}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="admin-page"><AdminHeading title="Auditoría" description="Registro de las acciones importantes. Los eventos no se pueden editar." /><section className="panel admin-filters"><Field label="Buscar en el registro"><Input value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} type="search" placeholder="Administrador, acción o identificador" /></Field></section><section className="panel"><QueryState pending={query.isPending} error={query.error} empty={!rows.length} onRetry={() => void query.refetch()} emptyText="No hay actividad registrada."><div className="admin-table-wrap"><table><thead><tr><th>Fecha</th><th>Administrador</th><th>Acción</th><th>Entidad</th></tr></thead><tbody>{rows.slice(page * 25, (page + 1) * 25).map(row => <tr key={row.id}><td>{dateTime(row.created_at)}</td><td>{row.actor_name || 'Sistema'}</td><td>{actionNames[row.action] || row.action.replaceAll('_', ' ').toLowerCase()}</td><td>{entityNames[row.entity_type] || row.entity_type}<small className="admin-id">{row.entity_id}</small></td></tr>)}</tbody></table></div></QueryState><Pagination page={page} count={rows.length} onChange={setPage} /></section></div>;
}
