import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowRightLeft, CheckCircle2, Eye, RefreshCw, XCircle } from 'lucide-react';
import { Button, Field, Input, Modal, Select, StatusBadge } from '../../components/ui';
import { useAvailability } from '../../hooks/useAvailability';
import { admin } from '../../services/admin';
import type { Availability, Reservation } from '../../types/domain';
import { formatDate, money, shortTime, todayLima } from '../../utils/date';
import { AdminHeading, dateTime, emptyFilters, Notice, Pagination, QueryState, ReservationFilterBar, useAdminCatalog, useDebounced, usePermissions, useRefreshAdmin } from './common';

export function ReservationDetails({ reservation, onClose, onChanged }: { reservation: Reservation; onClose: () => void; onChanged?: (next: Reservation) => void }) {
  const [current, setCurrent] = useState(reservation); const permissions = usePermissions(); const refresh = useRefreshAdmin();
  const [action, setAction] = useState<'cancel' | 'reschedule' | null>(null);
  const mutation = useMutation({ mutationFn: (kind: 'checkin' | 'cancel') => kind === 'checkin' ? admin.checkIn(current.reservation_code) : admin.cancel(current.id), onSuccess: result => { setCurrent(result); onChanged?.(result); setAction(null); void refresh(); } });
  const actionable = current.status === 'CONFIRMED';
  return <Modal title="Detalle de reserva" onClose={onClose} wide><div className="admin-reservation-code"><div><span className="kicker">CÓDIGO DE RESERVA</span><h3>{current.reservation_code}</h3></div><StatusBadge status={current.status} /></div><dl className="admin-detail-grid"><div><dt>Cliente</dt><dd>{current.first_name} {current.last_name}</dd></div><div><dt>DNI</dt><dd>{current.dni_masked || 'No registrado'}</dd></div><div><dt>Correo</dt><dd>{current.email}</dd></div><div><dt>Teléfono</dt><dd>{current.phone || 'No registrado'}</dd></div><div><dt>Sede / piscina</dt><dd>{current.venue_name} · {current.pool_name}</dd></div><div><dt>Carril</dt><dd>{current.lane_number}</dd></div><div><dt>Fecha y horario</dt><dd>{formatDate(current.date)}<br />{shortTime(current.start_time)} – {shortTime(current.end_time)}</dd></div><div><dt>Tarifa</dt><dd>{money(current.price)}</dd></div><div><dt>Creada</dt><dd>{dateTime(current.created_at)}</dd></div><div><dt>Check-in</dt><dd>{current.checked_in_at ? dateTime(current.checked_in_at) : 'Pendiente'}</dd></div></dl><Notice error={mutation.error} success={mutation.isSuccess ? 'Reserva actualizada correctamente.' : undefined} />{actionable && <div className="admin-actions"><Button loading={mutation.isPending} onClick={() => mutation.mutate('checkin')}><CheckCircle2 size={16} /> Realizar check-in</Button>{permissions.canManage(current.venue_id) && <><Button variant="secondary" onClick={() => { setAction('reschedule'); mutation.reset(); }}><ArrowRightLeft size={16} /> Reprogramar</Button><Button variant="danger" onClick={() => { setAction('cancel'); mutation.reset(); }}><XCircle size={16} /> Cancelar reserva</Button></>}</div>}{action === 'cancel' && <div className="admin-confirm"><h3>¿Cancelar esta reserva?</h3><p>El carril quedará disponible para otra persona. Esta acción se registrará en auditoría.</p><div className="row"><Button variant="danger" loading={mutation.isPending} onClick={() => mutation.mutate('cancel')}>Confirmar cancelación</Button><Button variant="ghost" onClick={() => setAction(null)}>Volver</Button></div></div>}{action === 'reschedule' && <RescheduleForm reservation={current} onDone={next => { setCurrent(next); setAction(null); onChanged?.(next); }} />}</Modal>;
}
export function AvailabilityPicker({ initialPool, onSelect, selected }: { initialPool?: string; onSelect: (row: Availability | null) => void; selected: Availability | null }) {
  const catalog = useAdminCatalog(); const [date, setDate] = useState(todayLima()); const [pool, setPool] = useState(initialPool || '');
  const query = useAvailability(date, pool || undefined);
  const rows = query.data?.filter(row => row.status === 'AVAILABLE' && (!pool || row.pool_id === pool)) || [];
  return <div className="stack"><div className="admin-form-grid"><Field label="Nueva fecha"><Input type="date" min={todayLima()} required value={date} onChange={event => { setDate(event.target.value); onSelect(null); }} /></Field><Field label="Piscina"><Select value={pool} onChange={event => { setPool(event.target.value); onSelect(null); }}><option value="">Todas las piscinas</option>{catalog.data?.pools.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{catalog.data?.venues.find(venue => venue.id === item.venue_id)?.name} · {item.name}</option>)}</Select></Field></div><Notice error={catalog.error} /><QueryState pending={query.isPending} error={query.error} empty={!rows.length} emptyText="No hay carriles disponibles en esta fecha." onRetry={() => void query.refetch()}><Field label="Horario y carril disponibles"><Select value={selected ? `${selected.time_slot_id}:${selected.lane_id}` : ''} onChange={event => onSelect(rows.find(row => `${row.time_slot_id}:${row.lane_id}` === event.target.value) || null)}><option value="">Selecciona una alternativa</option>{rows.map(row => <option key={`${row.time_slot_id}:${row.lane_id}`} value={`${row.time_slot_id}:${row.lane_id}`}>{row.venue_name} · {row.pool_name} · {shortTime(row.start_time)}–{shortTime(row.end_time)} · Carril {row.number} · {money(row.price)}</option>)}</Select></Field></QueryState></div>;
}
function RescheduleForm({ reservation, onDone }: { reservation: Reservation; onDone: (next: Reservation) => void }) {
  const [selected, setSelected] = useState<Availability | null>(null); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: () => { if (!selected) throw new Error('Selecciona un carril disponible.'); return admin.reschedule(reservation.id, selected.lane_id, selected.time_slot_id); }, onSuccess: next => { void refresh(); onDone(next); } });
  return <section className="admin-confirm"><h3>Reprogramar reserva</h3><p className="muted">La disponibilidad se verificará de nuevo al confirmar.</p><AvailabilityPicker initialPool={reservation.pool_id} selected={selected} onSelect={setSelected} /><Notice error={mutation.error} /><Button disabled={!selected} loading={mutation.isPending} onClick={() => mutation.mutate()}>Confirmar reprogramación</Button></section>;
}
export function ReservationTable({ rows, onSelect }: { rows: Reservation[]; onSelect: (reservation: Reservation) => void }) {
  return <div className="admin-table-wrap"><table><thead><tr><th>Fecha / hora</th><th>Cliente</th><th>Sede / piscina</th><th>Carril</th><th>Estado</th><th>Check-in</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.date.split('-').reverse().join('/')}</strong><small>{shortTime(row.start_time)} – {shortTime(row.end_time)}</small></td><td><strong>{row.first_name} {row.last_name}</strong><small>{row.reservation_code}</small></td><td>{row.venue_name}<small>{row.pool_name}</small></td><td><span className="admin-lane-number">{row.lane_number}</span></td><td><StatusBadge status={row.status} /></td><td>{row.checked_in_at ? dateTime(row.checked_in_at) : '—'}</td><td><Button variant="ghost" aria-label={`Ver reserva ${row.reservation_code}`} onClick={() => onSelect(row)}><Eye size={17} /> Ver</Button></td></tr>)}</tbody></table></div>;
}
export function ReservationsPage() {
  const [filters, setFilters] = useState(emptyFilters); const [page, setPage] = useState(0); const [selected, setSelected] = useState<Reservation | null>(null); const settled = useDebounced(filters);
  const query = useQuery({ queryKey: ['admin', 'reservations', settled, page], queryFn: () => admin.reservations(settled, 25, page * 25), enabled: !!settled.from && !!settled.to, refetchInterval: 30_000 });
  return <div className="admin-page"><AdminHeading title="Reservas" description="Busca, consulta y gestiona las reservas de tus sedes." actions={<Button variant="secondary" loading={query.isFetching} onClick={() => void query.refetch()}><RefreshCw size={16} /> Actualizar</Button>} /><ReservationFilterBar value={filters} onChange={next => { setFilters(next); setPage(0); }} /><section className="panel"><div className="admin-section-heading"><h2>Registro de reservas</h2><span className="muted">{query.data?.total ?? '—'} resultados</span></div><QueryState pending={query.isPending} error={query.error} empty={!query.data?.rows.length} onRetry={() => void query.refetch()} emptyText="No encontramos reservas."><ReservationTable rows={query.data?.rows || []} onSelect={setSelected} /></QueryState><Pagination page={page} count={query.data?.total || 0} onChange={setPage} busy={query.isFetching} /></section>{selected && <ReservationDetails reservation={selected} onClose={() => setSelected(null)} />}</div>;
}
