import { useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { CalendarPlus, Pencil, Plus, Save } from 'lucide-react';
import { Button, Field, Input, Modal, Select } from '../../components/ui';
import { admin, type EditableEntity, type Schedule } from '../../services/admin';
import type { Json, Lane, Pool, Venue } from '../../types/domain';
import { todayLima } from '../../utils/date';
import { AdminHeading, Notice, offsetDate, QueryState, useAdminCatalog, usePermissions, useRefreshAdmin } from './common';

type CatalogEntity = 'venues' | 'pools' | 'lanes';
type CatalogRow = Venue | Pool | Lane;
const entityNames = { venues: 'Sedes', pools: 'Piscinas', lanes: 'Carriles' };
function CatalogEditor({ entity, row, onClose }: { entity: CatalogEntity; row: CatalogRow | null; onClose: () => void }) {
  const catalog = useAdminCatalog(); const permissions = usePermissions(); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: (data: Record<string, Json>) => admin.save(entity, data), onSuccess: () => { void refresh(); onClose(); } });
  const values = row as unknown as Record<string, Json> | null;
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const data: Record<string, Json> = { ...(row ? { id: row.id } : {}), name: String(form.get('name')).trim(), active: form.get('active') === 'on' };
    if (entity === 'venues') { data.address = String(form.get('address')); data.latitude = form.get('latitude') ? Number(form.get('latitude')) : null; data.longitude = form.get('longitude') ? Number(form.get('longitude')) : null; }
    if (entity === 'pools') { data.venue_id = String(form.get('venue_id')); data.description = String(form.get('description')); }
    if (entity === 'lanes') { data.pool_id = String(form.get('pool_id')); data.number = Number(form.get('number')); }
    mutation.mutate(data);
  }
  const defaultString = (key: string) => String(values?.[key] ?? '');
  return <Modal title={`${row ? 'Editar' : 'Crear'} ${entity === 'venues' ? 'sede' : entity === 'pools' ? 'piscina' : 'carril'}`} onClose={onClose}><form className="stack" onSubmit={submit}>{entity === 'pools' && <Field label="Sede"><Select name="venue_id" required defaultValue={defaultString('venue_id')} disabled={!!row}><option value="">Selecciona una sede</option>{catalog.data?.venues.filter(venue => permissions.canManage(venue.id)).map(venue => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</Select>{row && <input type="hidden" name="venue_id" value={defaultString('venue_id')} />}</Field>}{entity === 'lanes' && <Field label="Piscina"><Select name="pool_id" required defaultValue={defaultString('pool_id')} disabled={!!row}><option value="">Selecciona una piscina</option>{catalog.data?.pools.filter(pool => permissions.canManage(pool.venue_id)).map(pool => <option key={pool.id} value={pool.id}>{catalog.data?.venues.find(venue => venue.id === pool.venue_id)?.name} · {pool.name}</option>)}</Select>{row && <input type="hidden" name="pool_id" value={defaultString('pool_id')} />}</Field>}<Field label="Nombre"><Input name="name" required minLength={2} maxLength={100} defaultValue={row?.name || ''} /></Field>{entity === 'venues' && <><Field label="Dirección"><Input name="address" required maxLength={300} defaultValue={defaultString('address')} /></Field><div className="admin-form-grid"><Field label="Latitud (opcional)"><Input name="latitude" type="number" min={-90} max={90} step="any" defaultValue={defaultString('latitude')} /></Field><Field label="Longitud (opcional)"><Input name="longitude" type="number" min={-180} max={180} step="any" defaultValue={defaultString('longitude')} /></Field></div></>}{entity === 'pools' && <Field label="Descripción"><Input name="description" maxLength={500} defaultValue={defaultString('description')} /></Field>}{entity === 'lanes' && <Field label="Número de carril"><Input name="number" type="number" min={1} max={100} required defaultValue={defaultString('number')} /></Field>}<label className="admin-checkbox"><input type="checkbox" name="active" defaultChecked={row?.active ?? true} /> Activo y habilitado</label><p className="muted">Los elementos con reservas activas no se pueden desactivar.</p><Notice error={mutation.error || catalog.error} /><Button loading={mutation.isPending} type="submit"><Save size={16} /> Guardar cambios</Button></form></Modal>;
}
export function CatalogPage({ entity }: { entity: CatalogEntity }) {
  const query = useQuery({ queryKey: ['admin', entity], queryFn: () => admin.list(entity) }); const catalog = useAdminCatalog(); const permissions = usePermissions();
  const [editing, setEditing] = useState<{ entity: CatalogEntity; row: CatalogRow | null } | null>(null);
  function parent(row: CatalogRow) { if ('venue_id' in row) return catalog.data?.venues.find(venue => venue.id === row.venue_id)?.name; if ('pool_id' in row) { const pool = catalog.data?.pools.find(pool => pool.id === row.pool_id); return `${catalog.data?.venues.find(venue => venue.id === pool?.venue_id)?.name || ''} · ${pool?.name || ''}`; } return row.address; }
  function canEdit(row: CatalogRow) { return (entity === 'lanes' || permissions.superAdmin) && permissions.canManage('venue_id' in row ? row.venue_id : 'pool_id' in row ? catalog.data?.pools.find(pool => pool.id === row.pool_id)?.venue_id || '' : row.id); }
  return <div className="admin-page"><AdminHeading title={entityNames[entity]} description="Administra la infraestructura de la red y su estado de operación." actions={(entity === 'lanes' || permissions.superAdmin) && <Button onClick={() => setEditing({ entity, row: null })}><Plus size={16} /> {entity === 'venues' ? 'Nueva sede' : entity === 'pools' ? 'Nueva piscina' : 'Nuevo carril'}</Button>} /><section className="panel"><QueryState pending={query.isPending} error={query.error} empty={!query.data?.length} onRetry={() => void query.refetch()} emptyText={`Todavía no hay ${entityNames[entity].toLowerCase()} registradas.`}><div className="admin-table-wrap"><table><thead><tr><th>Nombre</th><th>{entity === 'venues' ? 'Dirección' : 'Ubicación'}</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{query.data?.map(row => <tr key={row.id}><td><strong>{'number' in row ? `Carril ${row.number} · ` : ''}{row.name}</strong></td><td>{parent(row)}</td><td><span className={`badge ${row.active ? 'status-available' : 'status-maintenance'}`}>{row.active ? 'Activo' : 'Inactivo'}</span></td><td>{canEdit(row) && <Button variant="ghost" onClick={() => setEditing({ entity, row })}><Pencil size={15} /> Editar</Button>}</td></tr>)}</tbody></table></div></QueryState></section>{editing && <CatalogEditor entity={editing.entity} row={editing.row} onClose={() => setEditing(null)} />}</div>;
}

const days = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
function ScheduleEditor({ schedule, onClose }: { schedule: Schedule | null; onClose: () => void }) {
  const catalog = useAdminCatalog(); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: (data: Record<string, Json>) => admin.save('schedule_templates', data), onSuccess: () => { void refresh(); onClose(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); mutation.mutate({ ...(schedule ? { id: schedule.id } : {}), pool_id: String(form.get('pool_id')), day_of_week: Number(form.get('day_of_week')), open_time: String(form.get('open_time')), close_time: String(form.get('close_time')), slot_minutes: Number(form.get('slot_minutes')), price: Number(form.get('price')), active: form.get('active') === 'on' }); }
  return <Modal title={schedule ? 'Editar horario' : 'Crear horario'} onClose={onClose}><form className="stack" onSubmit={submit}><Field label="Piscina"><Select name="pool_id" required defaultValue={schedule?.pool_id || ''}><option value="">Selecciona piscina</option>{catalog.data?.pools.map(pool => <option key={pool.id} value={pool.id}>{catalog.data?.venues.find(venue => venue.id === pool.venue_id)?.name} · {pool.name}</option>)}</Select></Field><Field label="Día de la semana"><Select name="day_of_week" defaultValue={schedule?.day_of_week ?? 1}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</Select></Field><div className="admin-form-grid"><Field label="Apertura"><Input type="time" name="open_time" required defaultValue={schedule?.open_time.slice(0, 5)} /></Field><Field label="Cierre"><Input type="time" name="close_time" required defaultValue={schedule?.close_time.slice(0, 5)} /></Field><Field label="Duración del bloque (minutos)"><Input type="number" name="slot_minutes" required min={15} max={240} defaultValue={schedule?.slot_minutes} /></Field><Field label="Tarifa por carril (S/)"><Input type="number" name="price" required min={0} step="0.01" defaultValue={schedule?.price} /></Field></div><label className="admin-checkbox"><input name="active" type="checkbox" defaultChecked={schedule?.active ?? true} /> Horario habilitado</label><p className="muted">Después de guardar, publica los bloques del rango deseado. Los bloques con reservas se conservan.</p><Notice error={mutation.error || catalog.error} /><Button type="submit" loading={mutation.isPending}>Guardar horario</Button></form></Modal>;
}
function SchedulesSection() {
  const query = useQuery({ queryKey: ['admin', 'schedule_templates'], queryFn: () => admin.list('schedule_templates') }); const catalog = useAdminCatalog(); const refresh = useRefreshAdmin();
  const [editing, setEditing] = useState<{ row: Schedule | null } | null>(null); const [remove, setRemove] = useState<Schedule | null>(null);
  const deletion = useMutation({ mutationFn: (id: string) => admin.remove('schedule_templates', id), onSuccess: () => { setRemove(null); void refresh(); } });
  const generation = useMutation({ mutationFn: (data: { pool: string; from: string; to: string }) => admin.generateSlots(data.pool, data.from, data.to), onSuccess: () => { void refresh(); } });
  function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); generation.mutate({ pool: String(form.get('pool')), from: String(form.get('from')), to: String(form.get('to')) }); }
  return <><section className="panel"><div className="admin-section-heading"><div><h2>Horarios y tarifas</h2><p className="muted">Plantillas semanales por piscina</p></div><Button variant="secondary" onClick={() => setEditing({ row: null })}><Plus size={16} /> Nuevo horario</Button></div><QueryState pending={query.isPending} error={query.error} empty={!query.data?.length} onRetry={() => void query.refetch()} emptyText="Aún no hay horarios configurados."><div className="admin-table-wrap"><table><thead><tr><th>Piscina</th><th>Día</th><th>Horario</th><th>Duración</th><th>Tarifa</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{query.data?.map(row => <tr key={row.id}><td>{catalog.data?.pools.find(pool => pool.id === row.pool_id)?.name}</td><td>{days[row.day_of_week]}</td><td>{row.open_time.slice(0, 5)}–{row.close_time.slice(0, 5)}</td><td>{row.slot_minutes} min</td><td>S/ {Number(row.price).toFixed(2)}</td><td>{row.active ? 'Activo' : 'Inactivo'}</td><td><div className="row"><Button variant="ghost" onClick={() => setEditing({ row })}>Editar</Button><Button variant="ghost" onClick={() => setRemove(row)}>Eliminar</Button></div></td></tr>)}</tbody></table></div></QueryState></section><section className="panel admin-settings-form"><h2>Publicar bloques de reserva</h2><p className="muted">Genera la disponibilidad según las plantillas, tarifas y feriados guardados.</p><form className="stack" onSubmit={generate}><div className="admin-filter-grid"><Field label="Piscina"><Select name="pool" required><option value="">Selecciona piscina</option>{catalog.data?.pools.filter(pool => pool.active).map(pool => <option key={pool.id} value={pool.id}>{catalog.data?.venues.find(venue => venue.id === pool.venue_id)?.name} · {pool.name}</option>)}</Select></Field><Field label="Desde"><Input name="from" type="date" required min={todayLima()} defaultValue={todayLima()} /></Field><Field label="Hasta"><Input name="to" type="date" required min={todayLima()} defaultValue={offsetDate(todayLima(), 30)} /></Field></div><Notice error={generation.error} success={generation.isSuccess ? `Publicación completada: ${generation.data} bloques procesados.` : undefined} /><Button type="submit" loading={generation.isPending}><CalendarPlus size={17} /> Publicar horarios</Button></form></section>{editing && <ScheduleEditor schedule={editing.row} onClose={() => setEditing(null)} />}{remove && <Modal title="Eliminar plantilla de horario" onClose={() => setRemove(null)}><p>Se eliminará la plantilla del {days[remove.day_of_week].toLowerCase()}. Los bloques ya publicados se conservan; utiliza mantenimiento para cerrarlos.</p><Notice error={deletion.error} /><Button variant="danger" loading={deletion.isPending} onClick={() => deletion.mutate(remove.id)}>Eliminar plantilla</Button></Modal>}</>;
}
function HolidaysSection() {
  const query = useQuery({ queryKey: ['admin', 'holidays'], queryFn: () => admin.list('holidays') }); const catalog = useAdminCatalog(); const refresh = useRefreshAdmin(); const [creating, setCreating] = useState(false); const [remove, setRemove] = useState<string | null>(null);
  const save = useMutation({ mutationFn: (data: Record<string, Json>) => admin.save('holidays', data), onSuccess: () => { void refresh(); setCreating(false); } });
  const deletion = useMutation({ mutationFn: (id: string) => admin.remove('holidays', id), onSuccess: () => { void refresh(); setRemove(null); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); save.mutate({ venue_id: String(form.get('venue_id')) || null, date: String(form.get('date')), reason: String(form.get('reason')) }); }
  return <section className="panel"><div className="admin-section-heading"><div><h2>Feriados y cierres especiales</h2><p className="muted">Días excluidos de la generación de horarios</p></div><Button variant="secondary" onClick={() => { save.reset(); setCreating(true); }}>Agregar cierre</Button></div><QueryState pending={query.isPending} error={query.error} empty={!query.data?.length} emptyText="No hay feriados registrados."><div className="admin-table-wrap"><table><thead><tr><th>Fecha</th><th>Sede</th><th>Motivo</th><th>Acciones</th></tr></thead><tbody>{query.data?.map(row => <tr key={row.id}><td>{row.date}</td><td>{row.venue_id ? catalog.data?.venues.find(venue => venue.id === row.venue_id)?.name : 'Todas las sedes'}</td><td>{row.reason}</td><td><Button variant="ghost" onClick={() => setRemove(row.id)}>Eliminar</Button></td></tr>)}</tbody></table></div></QueryState>{creating && <Modal title="Agregar feriado o cierre" onClose={() => setCreating(false)}><form className="stack" onSubmit={submit}><Field label="Fecha"><Input name="date" type="date" required min={todayLima()} /></Field><Field label="Sede"><Select name="venue_id" required><option value="">Selecciona una sede</option>{catalog.data?.venues.map(venue => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</Select></Field><Field label="Motivo"><Input name="reason" required minLength={3} maxLength={300} /></Field><p className="muted">El cierre afecta también a los bloques publicados. Resuelve primero las reservas y bloqueos temporales de esa fecha.</p><Notice error={save.error} /><Button type="submit" loading={save.isPending}>Guardar cierre</Button></form></Modal>}{remove && <Modal title="Eliminar cierre" onClose={() => setRemove(null)}><p>La fecha podrá incluirse en futuras publicaciones de horarios.</p><Notice error={deletion.error} /><Button variant="danger" loading={deletion.isPending} onClick={() => deletion.mutate(remove)}>Confirmar eliminación</Button></Modal>}</section>;
}
function PoliciesSection() {
  const query = useQuery({ queryKey: ['admin', 'settings'], queryFn: () => admin.list('settings') }); const refresh = useRefreshAdmin();
  const mutation = useMutation({ mutationFn: (data: Record<string, Json>) => admin.save('settings' as EditableEntity, data), onSuccess: () => { void refresh(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); mutation.mutate({ id: 1, cancellation_hours: Number(form.get('cancellation_hours')), booking_days: Number(form.get('booking_days')), checkin_early_minutes: Number(form.get('checkin_early_minutes')), reschedule_enabled: form.get('reschedule_enabled') === 'on' }); }
  const settings = query.data?.[0];
  return <section className="panel admin-settings-form"><h2>Políticas de reserva</h2><p className="muted">Reglas generales para toda la red de piscinas.</p><QueryState pending={query.isPending} error={query.error} empty={!settings} onRetry={() => void query.refetch()}>{settings && <form className="stack" onSubmit={submit}><div className="admin-form-grid"><Field label="Anticipación para cancelar (horas)"><Input type="number" name="cancellation_hours" required min={0} max={168} defaultValue={settings.cancellation_hours} /></Field><Field label="Días disponibles para reservar"><Input type="number" name="booking_days" required min={1} max={180} defaultValue={settings.booking_days} /></Field><Field label="Anticipación para check-in (minutos)"><Input type="number" name="checkin_early_minutes" required min={0} max={120} defaultValue={settings.checkin_early_minutes} /></Field></div><label className="admin-checkbox"><input name="reschedule_enabled" type="checkbox" defaultChecked={settings.reschedule_enabled} /> Permitir reprogramación de reservas</label><Notice error={mutation.error} success={mutation.isSuccess ? 'Políticas guardadas.' : undefined} /><Button type="submit" loading={mutation.isPending}><Save size={16} /> Guardar políticas</Button></form>}</QueryState></section>;
}
export function SettingsPage() { const { superAdmin } = usePermissions(); const [tab, setTab] = useState('schedules'); return <div className="admin-page"><AdminHeading title="Configuración" description="Define horarios, tarifas, cierres y políticas de operación." /><div className="admin-range-tabs">{[['schedules', 'Horarios y tarifas'], ['holidays', 'Feriados'], ['policies', 'Reglas de reserva']].filter(([key]) => key !== 'policies' || superAdmin).map(([key, label]) => <Button key={key} variant={tab === key ? 'primary' : 'ghost'} onClick={() => setTab(key)}>{label}</Button>)}</div>{tab === 'schedules' ? <SchedulesSection /> : tab === 'holidays' ? <HolidaysSection /> : <PoliciesSection />}</div>; }
